[2024-10-22T00:18:00.650+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-22T00:18:00.672+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_crypto_pipeline.extract_crypto_data scheduled__2024-10-21T00:00:00+00:00 [queued]>
[2024-10-22T00:18:00.694+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_crypto_pipeline.extract_crypto_data scheduled__2024-10-21T00:00:00+00:00 [queued]>
[2024-10-22T00:18:00.696+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-10-22T00:18:00.723+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_crypto_data> on 2024-10-21 00:00:00+00:00
[2024-10-22T00:18:00.786+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=679) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-22T00:18:00.790+0000] {standard_task_runner.py:72} INFO - Started process 681 to run task
[2024-10-22T00:18:00.790+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_crypto_pipeline', 'extract_crypto_data', 'scheduled__2024-10-21T00:00:00+00:00', '--job-id', '185', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmpb5pziue9']
[2024-10-22T00:18:00.794+0000] {standard_task_runner.py:105} INFO - Job 185: Subtask extract_crypto_data
[2024-10-22T00:18:00.847+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_crypto_pipeline.extract_crypto_data scheduled__2024-10-21T00:00:00+00:00 [running]> on host df68927c17b4
[2024-10-22T00:18:00.955+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_crypto_pipeline' AIRFLOW_CTX_TASK_ID='extract_crypto_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-21T00:00:00+00:00'
[2024-10-22T00:18:00.957+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-22T00:18:01.313+0000] {logging_mixin.py:190} INFO - Dolar prices saved to parquet
[2024-10-22T00:18:04.355+0000] {logging_mixin.py:190} INFO - Crypto prices saved to parquet
[2024-10-22T00:25:25.071+0000] {job.py:229} INFO - Heartbeat recovered after 418.89 seconds
[2024-10-22T00:25:28.992+0000] {logging_mixin.py:190} INFO - ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[2024-10-22T00:25:28.998+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/../scripts/etl.py", line 59, in extract_crypto_data
    market_cap = data['data'][id]['quote']['USD']['market_cap']
                 ~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[2024-10-22T00:25:29.045+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=etl_crypto_pipeline, task_id=extract_crypto_data, run_id=scheduled__2024-10-21T00:00:00+00:00, execution_date=20241021T000000, start_date=20241022T001800, end_date=20241022T002529
[2024-10-22T00:25:29.073+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-22T00:25:29.075+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 185 for task extract_crypto_data ('NoneType' object is not subscriptable; 681)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/../scripts/etl.py", line 59, in extract_crypto_data
    market_cap = data['data'][id]['quote']['USD']['market_cap']
                 ~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[2024-10-22T00:25:29.118+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-22T00:25:29.162+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-22T00:25:29.167+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
