[2024-10-20T22:16:51.633+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-20T22:16:51.654+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transform_load_crypto_data.transform_load_crypto_data manual__2024-10-20T00:00:10+00:00 [queued]>
[2024-10-20T22:16:51.663+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transform_load_crypto_data.transform_load_crypto_data manual__2024-10-20T00:00:10+00:00 [queued]>
[2024-10-20T22:16:51.664+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-20T22:16:51.669+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): transform_load_crypto_data> on 2024-10-20 00:00:10+00:00
[2024-10-20T22:16:51.675+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=98) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-20T22:16:51.676+0000] {standard_task_runner.py:72} INFO - Started process 100 to run task
[2024-10-20T22:16:51.677+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'transform_load_crypto_data', 'transform_load_crypto_data', 'manual__2024-10-20T00:00:10+00:00', '--job-id', '163', '--raw', '--subdir', 'DAGS_FOLDER/dag_transform_load.py', '--cfg-path', '/tmp/tmpbtew19_x']
[2024-10-20T22:16:51.680+0000] {standard_task_runner.py:105} INFO - Job 163: Subtask transform_load_crypto_data
[2024-10-20T22:16:51.702+0000] {task_command.py:467} INFO - Running <TaskInstance: transform_load_crypto_data.transform_load_crypto_data manual__2024-10-20T00:00:10+00:00 [running]> on host 2eb6586dfd5f
[2024-10-20T22:16:51.735+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='transform_load_crypto_data' AIRFLOW_CTX_TASK_ID='transform_load_crypto_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-20T00:00:10+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-20T00:00:10+00:00'
[2024-10-20T22:16:51.735+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-20T22:16:55.888+0000] {logging_mixin.py:190} INFO - Dolar prices sent to DB
[2024-10-20T22:17:09.522+0000] {logging_mixin.py:190} INFO - Crypto prices sent to DB
[2024-10-20T22:17:09.536+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/../scripts/etl.py", line 93, in transform_load_crypto_data
    crypto_data = pd.read_parquet('/opt/airflow/data/crypto_data.parquet', index=False, engine='pyarrow')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 503, in read_parquet
    return impl.read(
           ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 251, in read
    result = self.api.parquet.read_table(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: read_table() got an unexpected keyword argument 'index'
[2024-10-20T22:17:09.602+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=transform_load_crypto_data, task_id=transform_load_crypto_data, run_id=manual__2024-10-20T00:00:10+00:00, execution_date=20241020T000010, start_date=20241020T221651, end_date=20241020T221709
[2024-10-20T22:17:09.628+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-20T22:17:09.630+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 163 for task transform_load_crypto_data (read_table() got an unexpected keyword argument 'index'; 100)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/../scripts/etl.py", line 93, in transform_load_crypto_data
    crypto_data = pd.read_parquet('/opt/airflow/data/crypto_data.parquet', index=False, engine='pyarrow')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 503, in read_parquet
    return impl.read(
           ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 251, in read
    result = self.api.parquet.read_table(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: read_table() got an unexpected keyword argument 'index'
[2024-10-20T22:17:09.733+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-20T22:17:09.754+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-20T22:17:09.755+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
